---
- hosts: target1
  connection: ssh
  become: yes
  become_method: sudo
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: install apache2
      apt:
        name: apache2
        state: latest
